import create from "zustand";

const useStore = create((set) => {
  return {
    setPage: (pageName, newState) =>
      set((state) => {
        const pageState = state[pageName];
        return { [pageName]: { ...pageState, ...newState } };
      }),
  };
});

export function updateStoreStateFromController(pageName, newState) {
  useStore.getState().setPage(pageName, newState);
}

const desktopModeProps = {
  ...{
  "Home": {
    "Flex1": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "10px",
        "paddingBottom": "10px",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "#1b0bf1",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "TextBox1": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "30px",
        "textAlign": "left",
        "color": "#ffffff",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Background Removing -  using Deep Learning"
      }
    },
    "Flex3": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "center",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "30px",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "30px",
        "paddingBottom": "30px",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex5": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "40px",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Upload1": {
      "onChange": false,
      "onClick": false,
      "styles": {
        "display": "",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "12px",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "8px",
        "paddingBottom": "8px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "16px",
        "textAlign": "left",
        "color": "#fff",
        "opacity": "",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1890ff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": "pointer"
      },
      "custom": {
        "multiple": false,
        "showFilename": true,
        "text": "Upload",
        "disabled": false
      },
      "io": {
        "files": null
      }
    },
    "TextBox2": {
      "onClick": false,
      "styles": {
        "alignSelf": "center",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Upload the image!!!!"
      }
    },
    "Image2": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "300px",
        "height": "300px",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": "/app-assets/images.png"
      }
    },
    "Button1": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "8px",
        "paddingBottom": "8px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "16px",
        "textAlign": "center",
        "color": "#fff",
        "opacity": "",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1890ff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": "pointer"
      },
      "custom": {
        "text": "Remove Background"
      }
    }
  },
  "background-change": {
    "TextBox3": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "30px",
        "textAlign": "left",
        "color": "#ffffff",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Change Background Deep Learning in action"
      }
    },
    "Flex6": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "10px",
        "paddingBottom": "10px",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "#1b0bf1",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex7": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "flex-start",
        "justifyContent": "center",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "20%",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "50px",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex8": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "10px",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex9": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Image3": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "300px",
        "height": "300px",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "dashed",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": ""
      }
    },
    "Image4": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "300px",
        "height": "300px",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "alt": "No preview available",
        "src": ""
      }
    },
    "Upload3": {
      "onChange": false,
      "onClick": false,
      "styles": {
        "display": "",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "12px",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "8px",
        "paddingBottom": "8px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "16px",
        "textAlign": "left",
        "color": "#fff",
        "opacity": "",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1890ff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": "pointer"
      },
      "custom": {
        "multiple": false,
        "showFilename": true,
        "text": "Upload",
        "disabled": false
      },
      "io": {
        "files": null
      }
    }
  }
}};

const breakpointProps = {
  ...{
  "Home": {},
  "background-change": {}
}};

function getViewportDimension() {
  const width = Math.max(
    document.documentElement.clientWidth || 0,
    window.innerWidth || 0
  );
  const height = Math.max(
    document.documentElement.clientHeight || 0,
    window.innerHeight || 0
  );
  return { width, height };
}

function getEffectiveBreakpointWidths(pageName, windowWidth) {
  if (breakpointProps[pageName] === undefined) {
    return [];
  }
  const widths = Object.keys(breakpointProps[pageName]);
  return widths
    .filter((curr) => {
      return parseInt(curr) >= windowWidth;
    })
    .sort((a, b) => {
      return parseInt(a) - parseInt(b);
    });
}

/**
 *
 * effective props is combination of
 */
function getEffectivePropsForPage(pageName) {
  const { width } = getViewportDimension();
  // effectiveProps initially has local changes
  let effectiveProps = JSON.parse(
    JSON.stringify(useStore.getState()[pageName])
  );
  const effectiveWidths = getEffectiveBreakpointWidths(pageName, width);
  effectiveWidths.forEach((effectiveWidth) => {
    const compAliases = Object.keys(breakpointProps[pageName][effectiveWidth]);
    compAliases.forEach((compAlias) => {
      const propNames = Object.keys(
        breakpointProps[pageName][effectiveWidth][compAlias]
      );
      propNames.forEach((propName) => {
        effectiveProps[compAlias][propName] = {
          ...useStore.getState()[pageName][compAlias][propName],
          ...breakpointProps[pageName][effectiveWidth][compAlias][propName],
        };
      });
    });
  });
  return effectiveProps;
}

export function setEffectivePropsForPage(pageName) {
  const effectiveProps = getEffectivePropsForPage(pageName);
  useStore.getState().setPage(pageName, effectiveProps);
}

useStore.setState(desktopModeProps);

export default useStore;
